schema = 3

[mod]
  [mod."github.com/goccy/go-yaml"]
    version = "v1.16.0"
    hash = "sha256-RpDZTl7Rh6R2FDG7UChmtcHPUVb1J6lpbfUd7UD2uSM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/santhosh-tekuri/jsonschema"]
    version = "v1.2.4"
    hash = "sha256-xrbhBNsAKQAXEfivl81bXzPDzerI5kxLFgPk7YGiJoQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.9.1"
    hash = "sha256-dzEqquABE3UqZmJuj99244QjvfojS8cFlsPr/MXQGj0="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.6"
    hash = "sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI="
